### PR TITLE
Update to Codeigniter 2.2.1

### PR DESCRIPTION
**Pull request by veisis**
Need some testing.

### CODE REVIEW

**Comment by dauni** [comment]
Login seems not working.
It redirects to "en/en/admin/auth/login"

**Comment by veisis** [comment]
I tested. Admin is working.
Do you performed a clean installation?
Maybe problem with .htaccess RewriteBase?

**Comment by dauni** [comment]
I made a fresh installation of your repo from
https://github.com/veisis/ionize/tree/codeigniter-update

Maybe there are some additional changes?

**Comment by veisis** [comment]
which version of PHP you are using? PHP 5.6? With php 5.6 admin is not working. Will look for fix. I tested only with 5.3, 5.4 and 5.5.

**Comment by dauni** [comment]
I have here PHP 5.5.9-1ubuntu4.7

**Comment by veisis** [comment]
nginx, apache or something else? I will spin up VM and test Ubuntu.

**Comment by partikule** [comment]
With PHP 5.5.9, try this : 

in /system/core/Common.php : 
Line 244, replace : 
		return $_config[0] =& $config;

with : 
          $_config[0] =& $config;
		return $_config[0];

This should correct the "return by ref" CodeIgniter bug.
If you still have a problem, it comes from something else.

**Comment by dauni** [comment]
It seems, that i have already this setting:
ci-update-01

I'm using Mint, but is based on Ubuntu
Server version: Apache/2.4.7 (Ubuntu)
PHP 5.5.9-1ubuntu4.7
with no special settings

**Comment by veisis** [comment]
Found problem. It should work new. I did incremental update. Forgot to comment out $RTR->_set_routing() when updated from 2.2 to 2.2.1.
PHP 5.6 should work too.

**Comment by dauni** [comment]
Yep - it works now on my server

**Comment by partikule** [comment]
Branch has too much conflict to get pulled.
We will try this upgrade internally, if it brings something interresting.
Sorry about that.

**Pull request closed without merging**
