### PR TITLE
Tagmanager - Improved beautifier: move all scripts to bottom

### PR DESCRIPTION
**Pull request by kstenschke**
All script tags inside beautified HTML are now moved to the end of the body tag (improving the speed of DOM initialization)

### CODE REVIEW

**Comment by kstenschke** [comment]
thanks for the recent merges. i'll review/fix this PRs conflicts and re-request the merge

**Comment by partikule** [comment]
I merged thte next one before this one, sorry about that, but I guess a lot of methods are missing.
I will add them again from your code.

**Comment by kstenschke** [comment]
ok, thank you, let me know if the diff conflicts too much, than i'll just re-request the merge from the final diff to my local copy.

**Comment by partikule** [comment]
OK, I guess it will be easier for you. Can you do it ?

**Pull request closed without merging**
