### PR TITLE
improved UX on filemanager file select

### PR DESCRIPTION
**Pull request by jnbn**
changed button orders (primary action is single item select)

### CODE REVIEW

**Comment by partikule** [comment]
Buttons are diplayed with A HTML Dom elements in ionize.

**Comment by jnbn** [comment]
I already know that buttons are displayed with it...

It was just an usability issue and order change.

I think I couldnt get what u meant...

**Comment by partikule** [comment]
... but you replaced the "A" tag by a "button" tag...
Please re-pul your change, but by keeping the "A" element, and I will accept it.

Sorry about that.

**Comment by jnbn** [comment]
Oh I see. I think I missed it.. I'll check asap

**Comment by partikule** [comment]
You're welcome ! :-)

**Pull request closed without merging**
